# Generated by Django 5.1.2 on 2024-10-31 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=11, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('payment_type', models.CharField(blank=True, choices=[('ONE_TIME', 'One Time'), ('PERIODIC', 'Periodic')], max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'account_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JournalVoucherAccountEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('journal_voucher_account_id', models.BigIntegerField()),
                ('accountable_id', models.BigIntegerField()),
                ('accountable_type_id', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'journal_voucher_account_entities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reference_number', models.CharField(blank=True, default='NULL', max_length=100)),
                ('exchange_rate', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('SALES_INVOICE', 'Sales Invoice'), ('RECEIPT', 'Receipt')], default='SALES_INVOICE', max_length=20)),
                ('transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=20, null=True)),
                ('control_number', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_vouchers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JournalVoucherAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2)),
                ('narration', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_used_set', to='accounts.account')),
                ('journal_voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_set', to='accounts.journalvoucher')),
            ],
            options={
                'db_table': 'journal_voucher_accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_defined', models.BooleanField(default=False)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_accounts_groups_set', to='accounts.accountgroup')),
            ],
            options={
                'db_table': 'sub_accounts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='sub_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_set', to='accounts.subaccount'),
        ),
    ]
