# Generated by Django 5.1.2 on 2024-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_currency_journalvoucher_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvoucheraccountentity',
            name='accountable_type_id',
            field=models.BigIntegerField(),
        ),
    ]
