# Generated by Django 5.1.2 on 2024-10-31 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_journalvoucheraccountentity_accountable_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalvoucheraccountentity',
            name='journal_voucher_account_id',
        ),
        migrations.AddField(
            model_name='journalvoucheraccountentity',
            name='journal_voucher_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities_set', to='accounts.journalvoucheraccount'),
        ),
    ]
