# Generated by Django 5.1.2 on 2024-11-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_subaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvoucheraccountentity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
