# Generated by Django 5.1.2 on 2024-11-01 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_journalvoucheraccountentity_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="sub_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_set",
                to="accounts.subaccount",
            ),
        ),
        migrations.AlterField(
            model_name="journalvoucher",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currency_used_set",
                to="accounts.currency",
            ),
        ),
        migrations.AlterField(
            model_name="journalvoucher",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="journalvoucheraccount",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_used_set",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="journalvoucheraccount",
            name="journal_voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_set",
                to="accounts.journalvoucher",
            ),
        ),
        migrations.AlterField(
            model_name="journalvoucheraccountentity",
            name="journal_voucher_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities_set",
                to="accounts.journalvoucheraccount",
            ),
        ),
        migrations.AlterField(
            model_name="subaccount",
            name="account_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_accounts_groups_set",
                to="accounts.accountgroup",
            ),
        ),
    ]
