# Generated by Django 5.1.2 on 2024-11-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_sub_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvoucheraccount',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currency'),
        ),
    ]
