# Generated by Django 5.1.2 on 2024-11-02 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='account_type',
            field=models.CharField(choices=[('SALES_ACCOUNT', 'Sales Account'), ('COST_OF_GOODS_SOLD', 'Cost of Goods Sold'), ('STORE_ACCOUNT', 'Store Account'), ('DISCOUNT_ALLOWED_ACCOUNT', 'Discount Allowed Account'), ('STOCK_ADJUSTMENT_ACCOUNT', 'Stock Adjustment Account'), ('ROUND_OFF_ACCOUNT', 'Round Off Account'), ('DISCOUNT_RECEIVED_ACCOUNT', 'Discount Received Account'), ('WRITE_OFF_ACCOUNT', 'Write Off Account'), ('EMPLOYEE_ADVANCE_ACCOUNT', 'Employee Advance Account'), ('DEFERRED_REVEUE_ACCOUNT', 'Deferred Revenue Account'), ('DEFERRED_EXPENSE_ACCOUNT', 'Deferred Expense Account'), ('STOCK_RECEIVED_BUT_NOT_BILLED', 'Stock Received But Not Billed'), ('EXPENSES_INCLUDED_IN_VALUATION', 'Expenses Included in Valuation'), ('VAT_ACCOUNT', 'VAT Account'), ('DEBTOR_ACCOUNT', 'Debtor Account'), ('CREDITOR_ACCOUNT', 'Creditor Account'), ('TRANST_LOSS_ACCOUNT', 'Transportation Loss Account')], default='SALES_ACCOUNT', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalvoucheraccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_used_set', to='accounts.companyaccount'),
        ),
    ]
