# Generated by Django 5.1.2 on 2024-11-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_companyaccount_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalvoucheraccount',
            name='account',
        ),
        migrations.AddField(
            model_name='journalvoucheraccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
