# Generated by Django 5.1.2 on 2024-11-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_journalvoucheraccount_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvoucher',
            name='exchange_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
