# Generated by Django 5.1.2 on 2024-11-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_subaccount_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalvoucheraccount',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_accounts_set', to='accounts.account'),
        ),
    ]
