# Generated by Django 5.1.2 on 2024-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_account_id_journalvoucheraccount_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
