# Generated by Django 5.1.2 on 2024-11-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_journalvoucher_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalvoucher',
            name='amount',
        ),
    ]
