# Generated by Django 5.1.2 on 2024-11-04 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_journalvoucheraccount_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='account_type',
            field=models.CharField(choices=[('CASH_IN_HAND', 'CASH IN HAND'), ('BANK', 'BANK'), ('SALES_ACCOUNT', 'Sales Account'), ('COST_OF_GOODS_SOLD', 'Cost of Goods Sold'), ('STORE_ACCOUNT', 'Store Account'), ('DISCOUNT_ALLOWED_ACCOUNT', 'Discount Allowed Account'), ('STOCK_ADJUSTMENT_ACCOUNT', 'Stock Adjustment Account'), ('ROUND_OFF_ACCOUNT', 'Round Off Account'), ('DISCOUNT_RECEIVED_ACCOUNT', 'Discount Received Account'), ('WRITE_OFF_ACCOUNT', 'Write Off Account'), ('EMPLOYEE_ADVANCE_ACCOUNT', 'Employee Advance Account'), ('DEFERRED_REVEUE_ACCOUNT', 'Deferred Revenue Account'), ('DEFERRED_EXPENSE_ACCOUNT', 'Deferred Expense Account'), ('STOCK_RECEIVED_BUT_NOT_BILLED', 'Stock Received But Not Billed'), ('EXPENSES_INCLUDED_IN_VALUATION', 'Expenses Included in Valuation'), ('VAT_ACCOUNT', 'VAT Account'), ('DEBTOR_ACCOUNT', 'Debtor Account'), ('CREDITOR_ACCOUNT', 'Creditor Account'), ('TRANST_LOSS_ACCOUNT', 'Transportation Loss Account')], default='SALES_ACCOUNT', max_length=50),
        ),
        migrations.CreateModel(
            name='SalesConfirmationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_confirmation_id', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('journal_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_transactions_set', to='accounts.journalvoucher')),
            ],
            options={
                'db_table': 'sales_confirmation_transactions',
                'managed': True,
            },
        ),
    ]
