# Generated by Django 5.1.2 on 2024-11-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_journalvoucheraccount_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalvoucheraccountentity',
            unique_together={('journal_voucher_account', 'accountable_id')},
        ),
        migrations.AlterUniqueTogether(
            name='salesconfirmationtransaction',
            unique_together={('journal_voucher', 'sales_confirmation_id')},
        ),
    ]
