# Generated by Django 5.1.2 on 2024-11-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_account_payment_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesconfirmationtransaction',
            unique_together=set(),
        ),
    ]
