# Generated by Django 5.1.2 on 2024-11-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_salesconfirmationtransaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvoucher',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='reference_number',
            field=models.CharField(blank=True, default='NULL', max_length=100, null=True),
        ),
    ]
